title: My virtual notes # your name (or website title) here
myname: >
  By Maria Paula Guillaumet
logo: "/images/portada_crop.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  After accumulating notebooks with my notes for years, I decided to make a virtual repository with my topics of interest. Here you can find a little of this and that.
  <br><br>
  Después de acumular por años cuadernos con mis notas, decidí hacer un repositorio virtual con mis temas de interés. Aquí podrán encontrar un poco de esto y aquello.
  <br><br>
  <a href="https://www.linkedin.com/in/paulaguillaumet/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-164144993-1 # your Google Analytics tracking ID  here
